// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");

function default_temperature_unit(param) {
  return /* C */0;
}

function default_temperature(uOpt, vOpt, param) {
  var u = uOpt !== undefined ? uOpt : /* C */0;
  var v = vOpt !== undefined ? vOpt : 0;
  return {
          u: u,
          v: v
        };
}

function default_request(desiredOpt, temperatureOpt, param) {
  var desired = desiredOpt !== undefined ? desiredOpt : /* C */0;
  var temperature = temperatureOpt !== undefined ? Caml_option.valFromOption(temperatureOpt) : undefined;
  return {
          desired: desired,
          temperature: temperature
        };
}

function default_response(param) {
  return {
          TAG: /* Error */0,
          _0: ""
        };
}

exports.default_temperature_unit = default_temperature_unit;
exports.default_temperature = default_temperature;
exports.default_request = default_request;
exports.default_response = default_response;
/* No side effect */
